### ISSUE TITLE
Encontrei alguns bugs e tenho algumas sugestões

### ISSUE THREAD

**Issue by parkournick3** [rmaci3l/Instanyan#11]
Vim porque a Janis pediu :rocket: 

## Bugs

1 - Na tela do meu note a responsividade não ficou boa![image](https://github.com/rmaci3l/Instanyan/assets/131922314/d70ef503-2292-4607-8ee2-67b5281fdc4a)

2 - Não tem feedback visual da validação da senha, com a senha `janislinda` dá erro 500 na api, com a senha `!.JanisLinda123` foi

## Sugestões

1. Eu revisaria as dependencias do frontend, algumas libs você pode colocar em "devDependencies" ao invés de "dependencies" isso diminue o bundle size em produção ( melhora a performance ), por exemplo, o tailwind poderia estar em "devDependencies" porque ele só funciona em dev mesmo, o eslint tb, já que é um lint, produção não precisa de lint... ( https://docs.npmjs.com/specifying-dependencies-and-devdependencies-in-a-package-json-file )
2. Migraria pro NextJs ou algum outro framework react, a propria documentação do react já recomenda isso, hoje em dia iniciar um projeto só em react não ta valendo muito a pena por varios motivos, é bom dar uma pesquisada ( https://react.dev/learn/start-a-new-react-project )
3. Acredito que a motivação do projeto é ter portifolio, eu mudaria esse ou escolheria django (https://www.djangoproject.com/) quando fosse fazer outro projeto, tem mais vaga, é parecido com rails pra caso queira aumentar seu curriculo :eyes:, e tb já tem muita coisa pronta, tem ORM propria... que inclusive eu acho bem melhor que o SQLAlchemy, pra projeto maior SQLAlchemy só meu deu problema.
4. Usaria https://fkhadra.github.io/react-toastify/introduction no frontend pra feedbacks visuais, senti falta de feedback nas ações do site, "login", "enviar post", "cadastro"... com um toast você pode mostrar que ta carregando, quando dá certo e quando dá errado.
5. Trocaria o Redux por ContextAPI ( feature do proprio react )
6. Usaria React-Query pra consumir a api ( https://tanstack.com/query/v3/ ), é um **asynchronous state management**, resumindo você poderia trocar todo seu código com Redux por algumas linhas com React-Query, outra vantagem é que o React-Query deixa tudo cacheado e só refaz a request quando precisa, por exemplo, se eu entrasse no seu site e ele tivesse com React-Query hoje eu veria os posts instantaneamente enquanto o react query estaria refazendo a request dos posts em background e quando carregasse novos posts eu veria os novos posts, isso melhora a experiencia do usuario e reduz as chamadas pra api drasticamente quando o projeto ta maior ( diminui custo de infra e deixa o site mais rapido )
7. BONUS: Um pouco mais complicado, mas seria legal ter um Dockerfile configurado pro server e pro frontend, seria mais fácil de rodar localmente e de deployar em clouds diferentes

Projeto ta TOP parabens :clap:

**Comment by rmaci3l** [comment]
Cara, valeu mesmo por ter dedicado esse tempo nas sugestões. Fiz um branch separado para corrigir os bugs que você mencionou também!

Eu só fui me ligar no Django ter mais adesão que o Flask quando já tava na metade do projeto. EAHUHEAU Mas Django sem dúvida tá na lista de coisas que pretendo estudar melhor, assim como o NextJS que você comentou!

Pretendo estudar melhor essas outras alternativas para consumir a API, visto que do jeito atual não está lá muito otimizado (notei que tá consumindo muita memória e fazendo requests desnecessárias D:). Vou corrigir isso num futuro próximo, creio.

No mais, obrigadão mesmo pelo feedback!!
